---
# YAML documents begin with the document separator ---
 
# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-
 
  # Hosts: where our play will run and options it will run with
  hosts: centos1
  gather_facts: False
 
  # Vars: variables that will apply to the play, on all target systems
  vars:
    named_list:
      - item1
      - item2
      - item3
      - item4
 
  # Tasks: the list of tasks that will be executed within the playbook
  tasks:
    - name: Test named list
      debug:
        msg: "{{ named_list }}"
 
    - name: Test named list first item dot notation
      debug:
        msg: "{{ named_list.0 }}"
 
    - name: Test named list first item brackets notation
      debug:
        msg: "{{ named_list[0] }}"
 
# Three dots indicate the end of a YAML document
...
