---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-

  # Hosts: where our play will run and options it will run with
  hosts: all

  # Tasks: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:

     - name: Play 1 - Task 1
       debug: 
         msg: Play 1 - Task 1

     - import_tasks: play1_task2.yaml

# Three dots indicate the end of a YAML document
...
