---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-

  # Hosts: where our play will run and options it will run with
  hosts: ubuntu-c
  
  # Tasks: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:
    - name: Pull python image
      docker_image:
        docker_host: tcp://docker:2375
        name: python:3.8.5
        source: pull

    - name: Create 3 python containers
      docker_container:
        docker_host: tcp://docker:2375
        name: "python{{ item }}"
        image: python:3.8.5
        container_default_behavior: no_defaults
        command: sleep infinity
      with_sequence: 1-3
-

  # Hosts: where our play will run and options it will run with
  hosts: containers
  gather_facts: False
  
  # Tasks: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:
    - name: Ping containers
      ping:

# Three dots indicate the end of a YAML document
...
