---
# YAML documents begin with the document separator ---
 
# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-
 
  # Hosts: where our play will run and options it will run with
  hosts: centos1
  gather_facts: False
 
  # Vars: variables that will apply to the play, on all target systems
  vars:
    dict:
      dict_key: This is a dictionary value
 
  # Tasks: the list of tasks that will be executed within the playbook
  tasks:
    - name: Test named dictionary dictionary
      debug:
        msg: "{{ dict }}"
 
    - name: Test named dictionary dictionary key value with dictionary dot notation
      debug:
        msg: "{{ dict.dict_key }}"
 
    - name: Test named dictionary dictionary key value with python brackets notation
      debug:
        msg: "{{ dict['dict_key'] }}"
 
# Three dots indicate the end of a YAML document
...
