---

- name: Installing services
  yum:
    name:
      - httpd
      - php
    state: present
- name: Ensure apache starts
  service: name=httpd state=started enabled=yes

- name: Upload application file
  copy:
    src: ../files/index.php
    dest: "{{ path_to_app }}"
    mode: '0755'
- name: Create simple info page
  copy:
    dest: "{{ path_to_app }}/info.php"
    content: "<h1> Info about our webserver, this is the first page {{ ansible_hostname }} </h1>"
- name: Configure php.ini file
  lineinfile:
    path: /etc/php.ini
    regexp: ^short_open_tag
    line: 'short_open_tag=On'
  notify: restart apache

