---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-

  # Hosts: where our play will run and options it will run with
  hosts: centos1

  # Tasks: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:

     - name: loop through list
       debug: 
         msg: "An item: {{item}}"
       with_sorted_items:
         - 3
         - 2
         - 1
         - Z
         - A
         - M

# Three dots indicate the end of a YAML document
...
