# setup-lb.yml

--- 
  - hosts: loadbalancers
    become: true 
    tasks:
      - name: Creating template
        template:
          src: ../config/lb-config.j2
          dest: /etc/httpd/conf.d/lb.conf
          owner: bin
          group: wheel
          mode: 064

      - name: restart apache
        service: name=httpd state=restarted 